"""empty message

Revision ID: 5490e9b9c3b7
Revises: 813288e4b576
Create Date: 2020-07-13 18:11:21.903268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5490e9b9c3b7'
down_revision = '813288e4b576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
